@startuml
node Jackal as j #Orange
title Merge features
frame "Items to insert" as fr {
    collections "Source collections" as sc #cbff5c
    folder "Source folder" as f #cbff5c
}
file "Source file" as sf #94afd1
file "Blank" as b #White
artifact "Output file" as o #94afd1
f -[dashed]down-o j
sc -[dashed]down-o j
sf -right-> j
j -right-> o
b -[dashed]up-> j


@enduml